# Usar la imagen oficial de Jenkins LTS (Long Term Support) como base
FROM jenkins/jenkins:lts

# Cambiar al usuario root para instalar paquetes
USER root

# Actualizar la lista de paquetes e instalar dependencias necesarias
RUN apt-get update && \  # Actualizar el índice de paquetes
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \  # Instalar herramientas para manejar repositorios HTTPS y otras utilidades
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \  # Descargar y añadir la clave GPG de Docker
    echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \  # Añadir el repositorio de Docker a la lista de fuentes
    apt-get update && \  # Actualizar el índice de paquetes nuevamente para incluir el repositorio de Docker
    apt-get install -y docker-ce && \  # Instalar Docker Community Edition
    usermod -aG docker jenkins  # Agregar el usuario jenkins al grupo docker para permitir su uso sin sudo

# Volver al usuario jenkins para ejecutar Jenkins
USER jenkins
